### ISSUE TITLE
Testing the algorithm on an arbitrary dataset

### ISSUE THREAD

**Issue by muberraozmen** [lrjconan/LanczosNetwork#3]
Hi!
Thanks for sharing your code! Would it be possible for you to mention about some preprocessing and setup rules that should be followed to test algorithms on an arbitrary dataset?

**Comment by lrjconan** [comment]
Thanks for your interests! I will add the support for testing on arbitrary graph datasets this week. Please stay tuned.

**Comment by congxie1108** [comment]
Hi!
Thanks for sharing the code.
Would it be possible for you to also add datasets such as cora, citeseer, and pubmed, so that we can reproduce the other results in the paper.
Not sure whether it will be covered in "the support for testing on arbitrary graph datasets".

**Comment by lrjconan** [comment]
> Hi!
> Thanks for sharing your code! Would it be possible for you to mention about some preprocessing and setup rules that should be followed to test algorithms on an arbitrary dataset?

I added the support now. Please read the instructions in the readme and the corresponding code. Please let me know if you have any questions. BTW, the question you raised is a bit inaccurate. As I did not run experiments on an arbitrary dataset in the paper, so there is no point for reproducing:)

**Comment by muberraozmen** [comment]
Thanks!

**Comment by lrjconan** [comment]
> Hi!
> Thanks for sharing the code.
> Would it be possible for you to also add datasets such as cora, citeseer, and pubmed, so that we can reproduce the other results in the paper.
> Not sure whether it will be covered in "the support for testing on arbitrary graph datasets".

Thanks for your interest! I added the support for general graph dataset. It should be straightforward for you to adapt it to cora etc. I generally do not trust the statistical significance of performances on cora etc. that much due to their [know issues](https://arxiv.org/pdf/1811.05868.pdf) for benchmarking graph networks. 

If you are interested, you can refer to some recent [independent work](https://arxiv.org/pdf/1902.07153.pdf) which successfully reproduce our results on cora etc.
